#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Cpanel-JSON-XS
Version  : 4.04
Release  : 1
URL      : https://cpan.metacpan.org/authors/id/R/RU/RURBAN/Cpanel-JSON-XS-4.04.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/R/RU/RURBAN/Cpanel-JSON-XS-4.04.tar.gz
Summary  : 'cPanel fork of JSON::XS, fast and correct serializing'
Group    : Development/Tools
License  : Artistic-1.0-Perl
Requires: perl-Cpanel-JSON-XS-bin
Requires: perl-Cpanel-JSON-XS-lib
Requires: perl-Cpanel-JSON-XS-man

%description
NAME
Cpanel::JSON::XS - cPanel fork of JSON::XS, fast and correct serializing
SYNOPSIS
use Cpanel::JSON::XS;

%package bin
Summary: bin components for the perl-Cpanel-JSON-XS package.
Group: Binaries
Requires: perl-Cpanel-JSON-XS-man

%description bin
bin components for the perl-Cpanel-JSON-XS package.


%package lib
Summary: lib components for the perl-Cpanel-JSON-XS package.
Group: Libraries

%description lib
lib components for the perl-Cpanel-JSON-XS package.


%package man
Summary: man components for the perl-Cpanel-JSON-XS package.
Group: Default

%description man
man components for the perl-Cpanel-JSON-XS package.


%prep
%setup -q -n Cpanel-JSON-XS-4.04

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/x86_64-linux-thread-multi/Cpanel/JSON/XS.pm
/usr/lib/perl5/site_perl/5.26.1/x86_64-linux-thread-multi/Cpanel/JSON/XS/Boolean.pm
/usr/lib/perl5/site_perl/5.26.1/x86_64-linux-thread-multi/Cpanel/JSON/XS/Type.pm

%files bin
%defattr(-,root,root,-)
/usr/bin/cpanel_json_xs

%files lib
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/x86_64-linux-thread-multi/auto/Cpanel/JSON/XS/XS.so

%files man
%defattr(-,root,root,-)
/usr/share/man/man1/cpanel_json_xs.1
/usr/share/man/man3/Cpanel::JSON::XS.3
/usr/share/man/man3/Cpanel::JSON::XS::Boolean.3
/usr/share/man/man3/Cpanel::JSON::XS::Type.3
